server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://162.14.82.200:3306/lever
    username: lever
    password: lever@123456
    hikari:
      max-lifetime: 300000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      password: lever@123456
      host: 162.14.82.200
      database: 0
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 20
logging:
  level:
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
