server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://162.14.82.200:3306/lever
    username: lever
    password: lever@123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
