server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://162.14.82.200:3306/lever
    username: lever
    password: lever@123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      password: lever@123456
      host: 162.14.82.200
      database: 0

logging:
  level:
    org.springframework.security: DEBUG
