name: Integration Tests
on: [ push, pull_request ]
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #        distribution: [ 'adopt', 'temurin', 'zulu' ]
        distribution: [ 'adopt' ]
        java: [ '17', '19' ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          check-latest: true
      - name: Run integration tests
        run: ./gradlew asciidoctor
      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Junit report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit
          fail-on-error: true